name: Deploy HTML via FTP

on:
  push:
    branches:
      - main # O la rama donde tengas tus archivos HTML (ej. master, develop)

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Usa la versión más reciente

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy@v2.0.0 # Usa la versión más reciente si hay una disponible
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Opcional: Si tu servidor FTP usa un puerto diferente al 21
          # port: ${{ secrets.FTP_PORT }}
          # Opcional: El directorio remoto en el servidor FTP donde se subirán los archivos
          # Puedes omitirlo si quieres subir a la raíz del usuario FTP
          remote_path: ${{ secrets.FTP_BASE_DIR }} # Asegúrate de que este secreto exista si lo usas