name: Custom FTP Deploy

on:
  push:
    branches:
      - main # O la rama donde tengas tus archivos HTML (ej. master, develop)

jobs:
  deploy:
    name: Run Custom FTP Deploy Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Obtener tu código

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Puedes especificar una versión específica como '3.9' o '3.10'

      - name: Configure FTP environment variables
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          # Opcional: Si quieres subir a un subdirectorio en el FTP
          FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }} # Asegúrate de que este secreto exista
          # Opcional: Si tus archivos HTML no están en la raíz de tu repositorio
          LOCAL_DIR: ./ # Por ejemplo, si tus HTML están en una carpeta 'dist', sería 'dist/'
        run: |
          echo "FTP_SERVER=${{ secrets.FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "FTP_REMOTE_PATH=${{ secrets.FTP_REMOTE_PATH }}" >> $GITHUB_ENV
          echo "LOCAL_DIR=./" >> $GITHUB_ENV # Asegúrate de que coincida con tu estructura de archivos

      - name: Run custom FTP deploy script
        run: python deployftp.py # O python scripts/deploy_ftp.py si lo guardaste en una subcarpeta